### ISSUE TITLE
Facets with facetRange only not working

### ISSUE THREAD

**Issue by Ryp007** [Gadoma/walmart-api-php-client#4]
In
class ProductService extends AbstractService implements ProductServiceInterface
public function getBySearch($phrase, $category = '', $facets = 'off', $facetFilter = '', $facetRange = '', $start = 1, $limit = self::DEFAULT_PAGE_SIZE, $sortField = self::DEFAULT_SORT_FIELD, $sortOrder = self::DEFAULT_SORT_ORDER)

```


if ($facets == 'on' && $facetFilter !== '') {
            $constraints['facet.filter'] = $facetFilter;

            if ($facetRange !== '') {
                $constraints['facet.range'] = $facetRange;
            }
        }

```

Should be replaced with

```

    if ($facets == 'on' ) {
            if( $facetFilter !== '')
                $constraints['facet.filter'] = $facetFilter;

            if ($facetRange !== '') {
                $constraints['facet.range'] = $facetRange;
            }
```

**Comment by ValeriiTsarov** [comment]
Is this project not supported?

**Comment by Gadoma** [comment]
@Lomaster it is supported 😈 A fix is on the way! 💃
